version: '2'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamfactory
      MYSQL_USER: df_admin
      MYSQL_PASSWORD: df_admin
    image: mysql
    networks:
      - net
    restart: always

  redis:
    image: redis
    networks:
      - net
    restart: always

  web:
    environment:
      SERVERNAME: dreamfactory.local
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_USERNAME: df_admin
      DB_PASSWORD: df_admin
      DB_DATABASE: dreamfactory
      CACHE_DRIVER: redis
      CACHE_HOST: redis
      CACHE_DATABASE: 0
      CACHE_PORT: 6379
    networks:
      - net
    volumes:
      - df-storage:/opt/dreamfactory/storage
    build: .
    ports:
      - "6380:80"
    restart: always

volumes:
  df-storage:
    driver: local

networks:
  net: